server:
  port: 5000

logging:
  level:
    com.example.pnuunivmiryangcampus : debug
    org.springframework.web.servlet : debug
    org.hibernate.type.descriptor.sql: trace

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pnu-univ-miryang-campus
    username: root
    password: 4789131l@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  h2.console.enabled: false
  sql.init.mode: always