server:
  port: 5000

logging:
  level:
    com.example.pnuunivmiryangcampus : debug
    org.springframework.web.servlet : debug
    org.hibernate.type.descriptor.sql: trace

spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/pnu-univ-miryang-campus
#    username: root
#    password: 4789131l@
#    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:h2:mem:test;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format-sql: true
        default-batch-fetch-size: 100
  h2.console.enabled: true
  sql.init.mode: always

feign:
  client:
    kakao:
      name: kakaoLogin
      base-url: https://kauth.kakao.com/oauth/
      auth-uri: authorize
      token-uri: token
      rest-api-key: b4610d35ecbcd2e97cadaac137434c74
      redirect-uri: http://localhost:5000/auth/callback
      grant-type: authorization_code



